name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 6.35.1

      - name: Set node version
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.2
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint test
        run: pnpm lint:fix

      - name: Build YAAW-for-Chrome
        run: pnpm build
